### ISSUE TITLE
GR6: Add additional policy checks to existing control

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#101]
**Is your feature request related to a problem? Please describe.**
PROTECTION OF DATA-AT-REST (M) needs more checks surrounding the Storage Accounts.

This module will detect the PBMM and look for specific policies not to be exempted. The compliance will fail right away if the PBMM policy is not applied. If applied, the following policies will be checked for exemptions:

- "TransparentDataEncryptionOnSqlDatabasesShouldBeEnabled"
- "DiskEncryptionShouldBeAppliedOnVirtualMachines"

**Describe the solution you'd like**
Could the following policy checks be added to the above list?

- "Storage accounts should restrict network access"
- "Secure transfer to storage accounts should be enabled"
- "Virtual machines should encrypt temp disks, caches, and data flows between Compute and Storage resources"

Q: What would we need to do to look at the policy results and determine if there are any failing resources?

**Comment by dutt0** [comment]
"Transparent Data Encryption on SQL databases should be enabled" is already in the required policy. Other two additional checks will be added replacing the deprecated.
