### ISSUE TITLE
Document Uploads Should Be Available in Multiple Formats

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#109]
**Is your feature request related to a problem? Please describe.**
Can only upload .txt files currently. Some use cases could require the use of a .docx or .png.

**Describe the solution you'd like**

- BreakGlassAccountProcedure,  GCPasswordGuidanceDoc,  PrivilegedAccountManagementPlan can be uploaded as a .txt or a .docx
-  ConfirmNetworkDiagramExists can be uploaded as a .png, .jpeg, .pdf etc.,
- GlobalAdministratorsUPN as a .txt
- All other attestations TBD. Consider removing or not evaluating the format of the file.

**Comment by dutt0** [comment]
Considering the option, 4th bullet point "not evaluating the format of the file" i.e. not considering what the file extension is.
If this were to be implemented, 1st three bullet points can be taken care of automatically to any format possible unless BreakGlassAccountProcedure, GCPasswordGuidanceDoc, PrivilegedAccountManagementPlan, ConfirmNetworkDiagramExists and GlobalAdministratorsUPN are needed to be restricted of only for the specific file formats as mentioned. 
Please confirm @MathesonSho

**Comment by MathesonSho** [comment]
In that case the only file that needs to be restricted to a specific format is the GlobalAdministratorsUPN as a .txt at this point.
