### ISSUE TITLE
Error Handling: GR9 errors in the workbook if no VNets are part of the tenant v1.1.8

### ISSUE THREAD

**Issue by amrinderssc** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#12]
**Describe the bug**
In the Dev Tenant, GR9 errors in the workbook if no VNets are part of the tenant

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/133687120/3db4d8fc-4ac5-48ad-8083-b7c90a8de421)

However, GR8 properly displays no subnets found and subscription name

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/133687120/0a60679e-efdd-4604-983b-d73f44f014d5)

**To Reproduce**
1. Install v1.1.8
2. Remove all Virtual Networks
3. Observe GR8 and GR9 in the workbook

**Comment by amrinderssc** [comment]
@singhgss @dutt0 appears VNet Compliance module is working as intended however, network watcher module displaying empty comment when no VNets found

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/133687120/3a51856e-b7c9-40bb-8035-175c81e1fcd9)

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/133687120/058a5155-b970-4ae5-906b-bd0cd91201e4)

**Comment by dutt0** [comment]
Re-opening the case as the issue "'project' operator: Failed to resolve scalar expression named 'VNETName_s'" in GR9 persists. 

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/7cd5ded8-b0ca-426f-ad93-57061f77b3b3)
