### ISSUE TITLE
GR1 | Validation 2| All Cloud User Accounts MFA Conditional Access Policy (M)

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#133]
ItemName ENG: “All Cloud User Accounts MFA Conditional Access Policy (M)”
ItemName FR: "Tous les comptes d’utilisateurs infonuagiques stratégie d’accès conditionnel AMF (M)"

**Description:** This is an existing control “Multi-Factor authentication required for all users by Conditional Access Policy” from GR3 in v1.0 Renamed to “All Cloud User Accounts MFA Conditional Access Policy (M)”. The intention is to ensure All User Accounts are adhering to a Conditional Access Policy enforcing MFA to login.

**Opportunities to Improve the Existing MFA Conditional Access Policy**
- Can there be more flexibility in what currently exists? For example 3.includedApplications this can be updated to 'All' OR contains 'Microsoft Admin Portals' 
- Do we need a deny CAP for users without MFA to make this a complete check?

>     # check for a conditional access policy which meets these requirements:
>     # 1. state =  'enabled'
>     # 2. includedUsers = 'All'
>     # 3. includedApplications = 'All'
>     # 4. grantControls.builtInControls contains 'mfa'
>     # 5. clientAppTypes contains 'all'
>     # 6. userRiskLevels = @()
>     # 7. signInRiskLevels = @()
>     # 8. platforms = null
>     # 9. locations = null
>     # 10. devices = null
>     # 11. clientApplications = null

**Optional Improvement:** How often is this CAP applied to end users? Every single time vs per session?

**Comment by alalvi00** [comment]
Update:

We will look to create a new control for the deny CAP

**Comment by MathesonSho** [comment]
Control already exists in v1.0.0 it's being moved GR3 to GR1 (includes a name change) with some opportunities to make it better. The first point is about making it more flexible. The second is asking if we should create a deny CAP to make it more robust. If so, we would have two checks. One that already exists and create a new one with deny controls instead.
