### ISSUE TITLE
GR2 | Validation 8 | Existing Guest User Accounts (M)

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#142]
ItemName: Existing Guest User Accounts (M)
ItemName FR: Comptes d'utilisateurs invités existants (M)

**Description**: This is an existing control reworded and is now required to be a default pass for all environments whether they use guest accounts or not. Current control is called “Remove Guest Accounts” new control name is “Existing Guest User Accounts (M)”. The control will list the guest user accounts for departments to verify their necessity overtime.

- List guest user accounts (no change)
- Default Compliant result (logic change required)

**Comment by MathesonSho** [comment]
Original Comment: Remove guest accounts from MS Entra ID or remove their permissions from the Azure Subscriptions.

New Comment: Review and validate list of guest users. Remove guest accounts according to departmental procedures and policies as needed. 

New Comment FR: Examinez et validez la liste des utilisateurs invités. Supprimez les comptes invités conformément aux procédures et politiques du service, au besoin.

**Comment by dutt0** [comment]
Additional column in the guest user table, where "True" for the guest account has at least one role assigned in a subscription and "False" for a guest account without any assigned role

**Comment by dutt0** [comment]
Additional new comments:
guestAssigned = This GUEST account has role assignment in the Azure subscriptions
guestNotAssigned = This GUEST account does not have any role assignment in the Azure subscriptions

**Comment by MathesonSho** [comment]
EN:
noGuestAccounts = There are currently no GUEST User Accounts in your tenant environment.
guestAccountsNoPermission = There are GUEST User Accounts in the tenant environment and they do not have any permissions in the tenant's Azure subscription(s).
guestAssigned = This GUEST User Account has a role assignment in the tenant's Azure subscriptions.
guestNotAssigned = This GUEST User Account does not have any role assignment in the tenant's Azure subscription(s).
existingGuestAccounts = Existing Guest User Accounts
existingGuestAccountsComment = Review and validate the provided list of GUEST User Accounts. Remove GUEST User Accounts according to your departmental procedures and policies, as needed.

FR:
noGuestAccounts = Il n’y a présentement aucun compte d’utilisateur invité dans votre environnement locataire.
guestAccountsNoPermission = Il y a des comptes d’utilisateurs invités dans l’environnement locataire et ils n’ont aucune permission dans le(s) abonnement(s) Azure du locataire.
guestAssigned = Ce compte d’utilisateur invité a une attribution de rôle dans le(s) abonnement(s) Azure du locataire.
guestNotAssigned = Ce compte d’utilisateur invité n’a pas d’attribution de rôle dans les abonnement(s) Azure du locataire.
existingGuestAccounts = Comptes d'utilisateurs invités existants
existingGuestAccountsComment = Examinez et validez la liste fournie des comptes d’utilisateurs invités. Supprimez les comptes d’utilisateurs invités selon les procédures et les politiques ministérielles, au besoin.
