### ISSUE TITLE
GR 3 | Validation 1 | Admin Access Restrictions Applied – Device Management/ Trusted Locations (M)

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#152]
ItemName: Admin Access Restrictions Applied – Device Management/ Trusted Locations (M)
ItemName FR: Restrictions d'accès administrateur appliquées – Gestion des appareils/Emplacements approuvés (M)

Description: This is a new control that will evaluate the environment’s conditional access policies. One of the environments CAPs will need to relate to named/ trusted locations. The other relating to device-based Conditional Access management (Target Resource and a condition for the device logging in). Both policies must include administrative users..

- “Is there a policy that uses any kind of device filter?” if yes, compliant.
- “Is there a policy that looks for a named/ trusted location?” if yes, compliant.
- "Do these policies include administrative users?" if yes, compliant.

**Comment by dutt0** [comment]
@alalvi00 Guardrail directory name and the other associated code needs to be renamed to match with [Government of Canada Cloud Guardrails- Canada.ca](https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32787)

**Comment by alalvi00** [comment]
Update:

For device filters:

Control needs to check if there are any applications that are included and device filter is enabled as a condition
