### ISSUE TITLE
GR6 | PBMM Policy Check | Comments and Subscription Logic

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#154]
Request: Focus on the logic for subscriptions and remove the roll-ups for management groups.

Detailed Test cases for “Transparent Data Encryption on SQL databases should be enabled”

1.	No resources but everything applied

Current Result= non-compliant

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/55abe861-0970-4fb9-a007-a066133e336f) 

Wanted Result = Compliant

Comments: PBMM initiative has been applied. Required Policy Definitions are not exempt. 0 Resources. 
 
2. No resources but 1 policy exempt on 1 subscriptions.
Current Result = Non-compliant
 
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/dd05c561-07f6-431a-b231-e602f6963374)

Wanted Result = Non-compliant
Comments: PBMM initiative has been applied. Exemption for policy definition name OR ID.
 
3. Create SQL Server without exemption. 
 
No issues. Use case is as intended.
 
4. SQL Server with an exemption. 
 Current Result = Non-compliant
 ![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/4da00484-4a59-4ede-9e5e-6e0dab812ab7)

Wanted Result = Non-compliant.
Comments: PBMM initiative has been applied. Exemption for policy definition name OR ID.

**Comment by MathesonSho** [comment]
EN:
noGuestAccounts = There are currently no GUEST User Accounts in your tenant.
guestAccountsNoPermission = There are GUEST User Accounts in the tenant and they don't have any permissions in the tenant's subscriptions.
guestAssigned = This GUEST User Accounts has a role assignment in the tenant's subscriptions.
guestNotAssigned = This GUEST User Accounts does not have any role assignment in the tenant's subscriptions.
existingGuestAccounts = Existing Guest User Accounts
existingGuestAccountsComment = Review and validate the provided list of GUEST User Accounts. Remove GUEST User Accounts according to your departmental procedures and policies as needed.
 
FR (TBD)
noGuestAccounts = Il n'y a aucun compte invité dans votre tenant
guestAccountsNoPermission = Il y a des comptes invités dans le tenant mais ils n'ont pas de permissions dans les abonnements Azure.
guestAssigned = ?
guestNotAssigned = ?
existingGuestAccounts = Comptes d'utilisateurs invités existants
existingGuestAccountsComment = Examinez et validez la liste des utilisateurs invités. Supprimez les comptes invités conformément aux procédures et politiques du service, au besoin.

**Comment by dutt0** [comment]
The test cases here are centered around policy. Unless we are updating the compliance reporting structure, we have to deduce the compliance results around each subscription as the results in CaC GR6. 
I shared an excel file @MathesonSho 

![Image](https://github.com/user-attachments/assets/e551431a-c348-497f-8500-802abe4b01f8)
