### ISSUE TITLE
GR2 | Validation 2 | Privileged Account Management Plan (Lifecycle of Account Management)

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#158]
GR2 |Validation 2 requires documentation to be uploaded to the storage account/ Attestation.

Document Titled "Privileged Account Management Plan". This is an existing control called "Privileged Account Management plan".

Need to determine whether this attestation will be kept in GR2 or moved to GR13.

**Assessor Note: Looking for a section on Lifecycle Management of accounts in the departmental policy/ document/

**Comment by dutt0** [comment]
Decision taken to keep in GR2

**Comment by dutt0** [comment]
Decision taken to keep in GR2
