### ISSUE TITLE
GR2 | Validation 4 | Privileged Account Management Plan (Least Privilege Role Assignment)

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#160]
GR2 |Validation 4 requires documentation to be uploaded to the storage account/ Attestation.

Document Titled "Privileged Account Management Plan". This is an existing control called "Privileged Account Management plan".

Need to determine whether this attestation will be kept in GR2 or moved to GR13.

**assessor note: Looking that least privilege roles are assigned and justified in the departmental Privileged Account Management Plan.

**Comment by dutt0** [comment]
Decision taken to keep in GR2
