### ISSUE TITLE
Workbook Mitigation Links to the Old Repository

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#19]
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/be6cff12-2cf2-43e7-b9a3-689cdf3b1d27)

Current links go to old repository and are broken.

Can we have the links open to the current repository following hyperlink to https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main/docs

Or once we update the controls document to that location.

**Comment by dutt0** [comment]
Thanks for including the screenshots @MathesonSho . We already have an issue created for this https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues/8

**Comment by MathesonSho** [comment]
Let's create this filepath to work and open as intended. The file can be a test file. 

https://[github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/docs/GUARDRAIL1-AC2-7.md](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/docs/GUARDRAIL1-AC2-7.md)

OR open to a generic location as suggested- because right now clients receive the following message
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/edd627e8-e07e-4c34-97fd-6e6f590c497e)
