### ISSUE TITLE
GR11 | Validation 5 |  Time Zone Configuration Consistency Check (M)

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#238]
Itemname: Time Zone Configuration Consistency Check (M)
Itemname FR: Vérification de cohérence de la configuration du fuseau horaire (M)

**Description:** The Time Zone Configuration Consistency Check is a mandatory control ensuring consistent time zone settings across all Azure applications and services. It identifies discrepancies that could cause data inconsistencies, scheduling issues, and compliance risks. By flagging deviations, it allows the relevant department to promptly address and correct them, ensuring smooth operations. This aligns with Guardrail 11’s Validation 5, which mandates configuring an appropriate time zone for audit records. 

Some of the Azure apps that can be configured with specific time zones include (confirm whether we’re able to read the TZ settings):
•	Azure App Services
•	Azure Virtual Machines (VMs)
•	Azure SQL Database
•	Azure Container Apps
•	Azure Functions
•	Azure Kubernetes Service (AKS)
•	Azure Logic Apps
•	Azure Data Factory
•	Azure Synapse Analytics
•	Azure Batch

**Suggested Flow:**
•	Check Time Zone Settings: The control will provide a list of each app and its configured time zone.
•	Determine Compliance: If there are three or more different time zones configured among the listed apps, the environment is non-compliant. If one time zone is used the majority of the time, the control should indicate that a time zone review may be required.
•	Report Results: Provide a list or table with the results of the time zone settings check.
•	Provide Comments: Explain any issues and suggest next steps for resolution.

| Use Case | Expected Result | 
| -------------- | :--------- | 
| All apps have the same timezone set. (not UTC) | Compliant. | 
| All apps have UTC timezone set. (default) | Compliant. | 
| The apps are using different timezones. 6 use UTC and 4 are ET | Compliant. Message indicating that a timezone review may be required as the apps are using two different TZs. | 
| The apps are using different timezones. 6 use UTC, 2 are ET, and 2 are PT | Non-compliant |

**Comment by dutt0** [comment]
Azure Virtual Machines (VMs) to complete this ticket.
There will be a separate ticket for the other Azure apps
