### ISSUE TITLE
GR2 | Validation 2 and Validation 4 | Questions/ Clarifications

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#249]
**Describe the bug**
Can only see one control that relates to the Privileged Account Management Plan in Guardrail 2. Additionally, there are some file formats we are not supporting for documents that aren't "read" by our tool. For example this file could be uploaded as a .pdf and the department would be non-compliant.

**To Reproduce**
1. Go to v2.1.0
2. Dev or Test

**Expected behavior**
Expected to see two controls in GR2 that rely on the Privileged Account Management Plan existing. 

1. Privileged Account Management Plan (Lifecycle of Account Management) (M)
2.  Privileged Account Management Plan (Least Privilege Role Assignment) (M)

**Screenshots**
![image](https://github.com/user-attachments/assets/e1a43693-9f76-429d-8413-df18001241d3)

**Questions**
- Are we going to have only one control for both validations?/ is this intentional?
- Can we be more flexible on format options for files that aren't being read by the CaC tool?

**Comment by dutt0** [comment]
1. We can either use one control (one attestation file) for both validations or two separate controls (two attestation files with different names)
2. Need to discuss the requirement for all attestation files. Currently, for a specific control pdf is supported; not all control

**Comment by MathesonSho** [comment]
1. One document attestation for both validations would be great. i.e., we should still see the 2 itemnames for both in the workbook and that they pass when that one file has been uploaded. 
2. Agreed that we should have a discussion. Overall thought is that we should only restrict format for files that our solution has to read/ grab information out of. to be continued..
