### ISSUE TITLE
Central Reporting: v2.0 data is not being collected automatically 

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#283]
**Describe the bug**
The current central reporting tooling is only collecting data from environments up to v1.2.3.  The LAW's custom logs do not have fields related to v2.0 changes.

**To Reproduce**
1. Install the central reporting components on dev tenant
2. connect the azure lighthouse bid from test to the dev tenant.
3. review dev tenant lighthouse clients. 
4. See successful onboarding
5. Go to central LAW in dev tenant
6. See missing Logs from test tenant

**Expected behavior**
We would expect to see the new fields in the custom logs and be able to collect v2.0 data. 

**Screenshots**
![image](https://github.com/user-attachments/assets/7dc4fafe-d91d-44f0-8aa3-c0eb0f3ee6dc)

![image](https://github.com/user-attachments/assets/cc6e50bd-b230-4854-bccc-5777f4ed3a37)

**Software versions used:**
 - Azure CaC v2.1.2

**Additional Context**
Review the central reporting demo for details on the current central reporting process.

**Comment by amrinderssc** [comment]
**Some validations that could help:**

- Ensure all the 2.x are reporting to the central tenant. (If Azure CaC is installed on 5, reports for all the 5 are on the central side)
- Ensure all the mandatory and optional controls are passed over to the central report. Any new items on the Azure CaC side, need to be part of the central report. 
- If possible, It is ideal to have all 2.x and 1.x reporting accurately in the central report. If not, 2.x would be the priority. 
- Once report is finalized, we might have to circle back with CCCS to ensure there integration still works. 
- If time permits, 163ent central tenant has a playbook that is built on top of the central law, that needs to be updated to reflect v2.x updates to the aggregated report.
