### ISSUE TITLE
GR1 | Validation 6 | comments and compliance mismatch

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#288]
**Describe the bug #1**
When a client has not uploaded the required file the comment does not explain what the client needs to do. It says the item name instead of the document name that it should be looking for.

**To Reproduce**
1. Go to any tenant
2. Remove “UserAccountsPrivilegedAndRegularUPN.csv ”
3. Run main runboook
4. See error in workbook

**Expected behavior**
Non-compliant and explains that you need to upload a file with the name “UserAccountsPrivilegedAndRegularUPN.csv ”

**Screenshots**
![image](https://github.com/user-attachments/assets/660facf8-adee-4e85-9d7d-a92bb58cda4c)
**Software versions used:**
- Azure CaC v2.1.2

**Describe the bug #2**
When a client has uploaded the required file but only included the highly privileged UPNs the comment does not explain that any fields are missing.

**To Reproduce**
1. Go to any tenant
2. Add the“UserAccountsPrivilegedAndRegularUPN.csv ” while only filling in the left most column with GA UPNs
3. Run main runboook
4. See error in workbook

**Expected behavior**
Non-compliant and explains that there are no UPNs for the non-privileged accounts.

**Software versions used:**
- Azure CaC v2.1.2

**Describe the bug #3**
When a client has uploaded the required file but only included the regular UPNs in the left most column the comment does not explain that any fields are missing.

**To Reproduce**
1. Go to any tenant
2. Add the“UserAccountsPrivilegedAndRegularUPN.csv ” while only filling in the left most column with regular account UPNs
3. Run main runboook
4. See error in workbook

**Expected behavior**
Result focused on the fact that there may be an account listed without GC privileges in the incorrect column which is good. However, it is missing the fact that there isn't a second column for the matching privileged and non-privileged UPNS.

Suggest updating the logic to ensure this is a non-compliant result

**Software versions used:**
- Azure CaC v2.1.2

**Additional context**
Use cases sent to you via email.

**Comment by dutt0** [comment]
@MathesonSho  The csv file format below:
![image](https://github.com/user-attachments/assets/0ac14192-e79b-4016-8287-890a9b8b6bbf)

**Comment by dutt0** [comment]
Bug #1 fix is in progress. 
Other reported bug here needs re-testing with the csv format above @MathesonSho. We might want to create a separate ticket if those exists
