### ISSUE TITLE
v1.1.9 GR 1: Item Name Changes

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#38]
![GR 1 2023-12-11](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/d70df975-c080-467f-953d-1d0d8e1ecf9e)

Guardrail 1- Item Name
1.	Break Glass Account Non-technical (M) --> Break Glass Account Procedure (M)
2.	Responsibility of break glass accounts must be with someone not-technical, director level or above (R) --->BG Responsibility Follows Department Procedure (R)

English ---> French
1. Break Glass Account Procedure (M) = Procédure de compte de bris de verre (M)
2. BG Responsibility Follows Department Procedure (R) = Responsabilité BV suit la procédure du ministère (R)

No logic changes. Just the names of the controls and attestations need to be updated.

Guardrail 1: Attestations
1.	 Break Glass Account Procedure (M)
------ BreakGlassAccountProcedure.txt
2.	BG Responsibility Follows Department Procedure (R)
------ BGFollowProcedureResponsibility.txt

**Comment by dutt0** [comment]
@MathesonSho can you please provide screenshots. Thanks

**Comment by MathesonSho** [comment]
Yes- updated as requested @dutt0

**Comment by MathesonSho** [comment]
Updated ticket with French text as well @dutt0

**Comment by dutt0** [comment]
Thanks @MathesonSho

**Comment by dutt0** [comment]
ItemName updated Screenshot from Test env.
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/4310c5ba-c14d-4b65-872f-6547848e082d)

Thanks @MathesonSho for the update on the issue on the attestation name. Will update the PR

**Comment by dutt0** [comment]
Screenshot from Test tenant

![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/d4bebd93-5bd1-4ffd-8dec-84888de439dd)
