### ISSUE TITLE
backend.ps1 erroring out Get-AzResourceGroup : Provided resource group does not exist

### ISSUE THREAD

**Issue by dutt0** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#5]
**Describe the bug**
The backend.ps1 is failing to parse the version number for checking an update availability. The reason behind the issue is that it can't find the resource group where the Automation Account variables are stored. This issue only occurs with customers who have multiple subscriptions. 

Note: It is fixed in MSFT Azure CaC PR#458  in the released version v1.1.8
Links to the original report: https://github.com/Azure/GuardrailsSolutionAccelerator/issues/458

**To Reproduce**
1. Go to the specific resource group
2. Click on 'backend'
3. Go to to 'Errors' tab

**Expected behavior**
That it should be able to parse the version number and it should be able to find the right resource group in the right subscription.

**Screenshots**
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/a137eee0-59a0-4a6e-843e-b126655cee65)

**Additional context**

**Comment by singhgss** [comment]
Fixed in https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pull/2
