### ISSUE TITLE
Match controls for both English & French versions

### ISSUE THREAD

**Issue by dutt0** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#55]
Match controls for both English & French versions for the following

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/d4bdbaa8-442d-43f6-bbbe-68c401132027)

and
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/d53bab0d-66d8-4b7a-93e2-9dbad209d4ae)

Current: French version 
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/53473eed-292f-4c21-9a28-307c38219f3c)

Expected:
ItemName should be present in French

**Comment by dutt0** [comment]
@MathesonSho @amrinderssc Please provide French verbose for the above (red marked) . Thanks.

**Comment by amrinderssc** [comment]
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/133687120/63f2865a-271f-497a-ab4f-29016f7ebcb4)

mfaEnforcement name review

**Comment by MathesonSho** [comment]
mfaEnforcement i.e. old MFA control check for BG account MFA is to be removed.

**Comment by MathesonSho** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MathesoS/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/MathesoS/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MathesoS/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-CA style='tab-interval:.5in;word-wrap:break-word'>



English | French
-- | --
procedureFileFound = File {0} found in Container. | = Fichier {0} trouvé dans le   conteneur.
procedureFileNotFound = Could not find document for {0}, please   create and upload a file with the name '{1}' in Container '{2}' on Storage   Account '{3}' to confirm you have completed the Item in the control. | = N’a pas trouvé de document pour   {0}, veuillez créer et télécharger un fichier avec le nom « {1} »   dans le conteneur « {2} » sur le compte de stockage   « {3} » pour confirmer que vous avez terminé l’élément dans le   contrôle.
procedureFileDataInvalid = The global administrator file(s)   contain(s) invalid User Principal Names (UPNs). Ensure that UPNs start with a   hyphen, and type each of them on a new line. | = Le(s) fichier(s) d’administrateur général contiennent des noms   principaux d’utilisateur non valides. Assurez-vous que les noms principaux   d’utilisateur commencent par un trait d’union et tapez chacun d’eux sur une   nouvelle ligne.
globalAdminFileFound = File {0} found in Container. | = Fichier {0} trouvé dans le   conteneur.
globalAdminFileNotFound = Could not find document for {0}, please   create and upload a file with the name '{1}' in Container '{2}' on Storage   Account '{3}' to confirm you have completed the Item in the control. | = N’a pas trouvé de document pour   {0}, veuillez créer et télécharger un fichier avec le nom « {1} » dans le   conteneur « {2} » sur le compte de stockage « {3} » pour confirmer que vous   avez terminé l’élément dans le contrôle.
globalAdminFileEmpty = Empty file {0} found in Container. | = Fichier vide {0} trouvé dans le   conteneur.
globalAdminNotExist = Global Administrator accounts not found or   declared in file {0}. | = Comptes d’administrateur général   non trouvés ou déclarés dans le fichier {0}.
globalAdminMFAPassAndMin2Accnts = Two or more global administrator   accounts have been identified, and multi-factor authentication (MFA) is   enabled for all of them. | = Deux comptes d’administrateur   général ou plus ont été identifiés et l’authentification multifacteur est   activée pour chacun d’eux.
globalAdminMinAccnts = There must be at least two global administrator   accounts. | = Il doit y avoir au moins deux   comptes d’administrateur général.
NEW: |  
globalAdminAccntsMFADisabled1 = The following account:   j###@a###.com does not have multi-factor authentication (MFA) enabled. | = Le compte suivant : j###@a###.com   n’a pas d’authentification multifacteur activée.
globalAdminAccntsMFADisabled2 = The following accounts:    j###@a###.com,  j###@a###.com,  j###@a###.com, and    j###@a###.com do not have multi-factor authentication (MFA) enabled | = Les comptes suivants :   j###@a###.com, j###@a###.com, j###@a###.com et j###@a####.com n’ont pas   d’authentification multifacteur activée
globalAdminAccntsMFADisabled3 = None of the global administrator   accounts have multi-factor authentication (MFA) enabled | = Aucun des comptes   d’administrateur global n’a l’authentification multifacteur activée




</body>

</html>

**Comment by dutt0** [comment]
Thanks @MathesonSho . Also need the French for "Global Administrators Accounts MFA check"
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/cbaaf54b-16e7-4d49-98b8-96e0cb820053)

**Comment by MathesonSho** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MathesoS/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/MathesoS/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MathesoS/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-CA style='tab-interval:.5in;word-wrap:break-word'>



English | French
-- | --
procedureFileFound = File {0} found in Container. | = Fichier {0} trouvé dans le   conteneur.
procedureFileNotFound = Could not find document for {0}, please   create and upload a file with the name '{1}' in Container '{2}' on Storage   Account '{3}' to confirm you have completed the Item in the control. | = N’a pas trouvé de document pour   {0}, veuillez créer et télécharger un fichier avec le nom « {1} »   dans le conteneur « {2} » sur le compte de stockage   « {3} » pour confirmer que vous avez terminé l’élément dans le   contrôle.
procedureFileDataInvalid = The global administrator file(s)   contain(s) invalid User Principal Names (UPNs). Ensure that UPNs start with a   hyphen, and type each of them on a new line. | = Le(s) fichier(s) d’administrateur général contiennent des noms   principaux d’utilisateur non valides. Assurez-vous que les noms principaux   d’utilisateur commencent par un trait d’union et tapez chacun d’eux sur une   nouvelle ligne.
globalAdminFileFound = File {0} found in Container. | = Fichier {0} trouvé dans le   conteneur.
globalAdminFileNotFound = Could not find document for {0}, please   create and upload a file with the name '{1}' in Container '{2}' on Storage   Account '{3}' to confirm you have completed the Item in the control. | = N’a pas trouvé de document pour   {0}, veuillez créer et télécharger un fichier avec le nom « {1} » dans le   conteneur « {2} » sur le compte de stockage « {3} » pour confirmer que vous   avez terminé l’élément dans le contrôle.
globalAdminFileEmpty = Empty file {0} found in Container. | = Fichier vide {0} trouvé dans le   conteneur.
globalAdminNotExist = Global Administrator accounts not found or   declared in file {0}. | = Comptes d’administrateur général   non trouvés ou déclarés dans le fichier {0}.
globalAdminMFAPassAndMin2Accnts = Two or more global administrator   accounts have been identified, and multi-factor authentication (MFA) is   enabled for all of them. | = Deux comptes d’administrateur   général ou plus ont été identifiés et l’authentification multifacteur est   activée pour chacun d’eux.
globalAdminMinAccnts = There must be at least two global administrator   accounts. | = Il doit y avoir au moins deux   comptes d’administrateur général.
NEW: |  
globalAdminAccntsMFADisabled1 = The following account:   j###@a###.com does not have multi-factor authentication (MFA) enabled. | = Le compte suivant : j###@a###.com   n’a pas d’authentification multifacteur activée.
globalAdminAccntsMFADisabled2 = The following accounts:    j###@a###.com,  j###@a###.com,  j###@a###.com, and    j###@a###.com do not have multi-factor authentication (MFA) enabled | = Les comptes suivants :   j###@a###.com, j###@a###.com, j###@a###.com et j###@a####.com n’ont pas   d’authentification multifacteur activée
globalAdminAccntsMFADisabled3 = None of the global administrator   accounts have multi-factor authentication (MFA) enabled | = Aucun des comptes   d’administrateur général n’a l’authentification multifacteur activée




</body>

</html>


Global Administrators Accounts MFA Check == Vérification d’authentification multifacteur de comptes d’administrateur général

**Comment by dutt0** [comment]
I would create a separate ticket for the new controls

![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/c92fdd8c-b1d8-48f9-871c-24ba110dc752)

**Comment by dutt0** [comment]
![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/413c592b-a53b-4ae5-bcef-6ad68a08b4b4)

![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/fe1ac498-6c08-4787-9772-e820e41ccea4)

![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/4f6ac2d9-6e87-4886-83ce-65d16eefa51d)

![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/f8fc3b40-421d-49d7-864c-2d4efbea0f69)
