### ISSUE TITLE
Remove old controls and add the new MFA check

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#56]
Remove MFA Enforcement Excl. Break Glass Accounts (M) from Guardrail 1 and 3

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/1112b5a2-fb5f-461a-8465-7726c87d981a)

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/eeaf8bb0-1cdc-4c1a-b98d-f2becf54b410)

Add Global Administrators Accounts MFA check (M) to Guardrail 1 and 3. Right now it's missing from Guardrail 3.

**Comment by dutt0** [comment]
Controls are updated.

![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/d3d19ab9-8277-4c30-b9bc-f0077199e92c)


![Image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/7f2a23e8-2fa0-495b-8b44-8699adafa5e2)
