### ISSUE TITLE
GR 1 & 3:  GA MFA Check Does Not Appear in Workbook

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#74]
**Describe the bug (s)**
1. When clients deploy the solution for the first time they have not uploaded any of the attestations. In this case, the Check-GAAuthenticationMethods will fail and not return any results to the workbook.

2. When clients upload the attestation with the wrong format. In this case, the module fails and it does not return any results to the workbook.

**To Reproduce**
A) Steps to reproduce the behavior:
1. Go to the storage account and remove the upn.txt file
2. Rerun main and backend runbooks
3. Review main logs for error
4. See error/ no resulting control for the GA MFA Check in the workbook.

B) Steps to reproduce the behavior:
1. Go to the storage account and upload the upn.txt file (2 in the correct format and 3 in the wrong i.e., without the hyphen)
3. Rerun main and backend runbooks
4. Review main logs for error
5. See error/ no resulting control for the GA MFA Check in the workbook.

**Expected behavior**
In the event that there is an error; the control should show as non-compliant and the module still runs. This would control would show up in the workbook as non-compliant.

**Screenshots**
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/984979e7-8bb0-420f-b6b2-7138d051b2ea)
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/81d48f2c-a89a-4595-b575-ee597f794f44)

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/bf1bd6d2-116e-488c-8341-81befc84811b)

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/1c5f18b1-70b4-40b4-83b4-62ca5f2ea909)

![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/111992749/913451dd-2286-486d-82d9-62f03c073d64)

**Comment by dutt0** [comment]
For this specific scenario (no GlobalAdministratorsUPN.txt in the storage account), the error in the error log is because of the Write-Error comment that was put in place for the developers to see the log. The workbook will still work as intended. 
However, since it may be creating a confusion, we will remove the print output.
