### ISSUE TITLE
Guardrail 11 Enhancement

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#82]
**Is your feature request related to a problem? Please describe.**
Current mandatory check for Guardrail 11 is not as robust as it could be. 

Mandatory Validations should be:
	Confirm policy for event logging is implemented.
	Confirm event logs are being generated.
	Confirm that security contact information has been configured to receive alerts and notifications.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
- Adding three attestations for each validation. 
- Creating use case indicators matching manual assessment-
      1. Show me a config screen on logging for x,y,and z events. ** Any event**. 
      2. Show me that data collected in MS Azure?
      3. Show me the email configured/ external storage of these notifications of events.
- Can we modify the existing mandatory checks to meet our needs?

**Additional context**
Original Request here: https://github.com/Azure/GuardrailsSolutionAccelerator/issues/214#issue-1425667758

**Comment by dutt0** [comment]
Closing the stale ticket as other new tickets for v2.0 issued.
