### ISSUE TITLE
Upcoming breaking change - fix needed

### ISSUE THREAD

**Issue by dutt0** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#9]
**Describe the bug**
This is currently shown as warning in the runbook. However, it mentions an upcoming breaking change.
"Upcoming breaking changes in the cmdlet 'Get-AzPolicyAssignment' : - The output type 'Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Policy.PsPolicyAssignment' is changing - The following properties are being added to the output type : 'Identity' "

**Screenshots**
![image](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/assets/147828743/a920c956-30bf-4e39-a09d-d2455f6bcabc)

**Expected behavior**
No warning will show

**Additional context**

**Comment by alalvi00** [comment]
The given warnings are only produced in the test tenant

**Comment by alalvi00** [comment]
These warnings are not seen in dev or test tenants
