### ISSUE TITLE
Preserve Attestations During Upgrades/Updates

### ISSUE THREAD

**Issue by MathesonSho** [ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#93]
**Is your feature request related to a problem? Please describe.**
Update process involves asking clients to delete the resource group and subsequent ties to the hosting tenant (Azure Lighthouse bids etc.,). Additionally, the deletion removes the Storage Account with the uploaded attestations/ files. 

**Describe the solution you'd like**
As per client feedback the feature request is to preserve attestations during upgrades/updates.

**Describe alternatives you've considered**
-  Client Suggestion: remove the storage account from being one of the deployed resources and ask departments to identify the storage account in the config.json that they'd like the tool to use to check for uploaded files/ attestations.
- Other development ideas

**Comment by dutt0** [comment]
Preserve Attestations during Upgrades/Updates in CI/CD pipeline
